### ISSUE TITLE
how boot?

### ISSUE THREAD

**Issue by dhaluza** [jhohisel/custom-ubuntu-arm64-livecd#1]
Hello. Can you write manual how boot? If i try load, with ubuntu kinetic live - Lenovo Thinkpad X13s menu
System not respose and in monitor this:
EFI stub: Booting Linux Kernel...
EFI stub: Using DTB from configuration table
EFI stub: Exiting boot services...

**Comment by grealish** [comment]
Have a read of this
https://docs.google.com/document/d/1WuxE-42ZeOkKAft5FuUk6C2fonkQ8sqNZ56ZmZ49hGI/mobilebasic#heading=h.d1689esafskyv

**Comment by jhohisel** [comment]
I suspect the issue is due to the DTB file not loading. It seems different configurations have different model numbers and it's likely that yours is not matching. I'll look into rebuilding with a different computed CHID that is more widely compatible.
